version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: bancodigital_db
    environment:
      POSTGRES_DB: bancodigital
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    command: postgres -c max_connections=20 -c shared_buffers=128MB -c work_mem=4MB -c effective_cache_size=512MB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d bancodigital"]
      interval: 5s
      timeout: 5s
      retries: 5